<?php

/**
 * Implémente hook_theme_suggestions_alter().
 */
function forms_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  if ($hook == 'form_element' && isset($variables['element']['#form_id'])) {
    if ($variables['element']['#form_id'] == 'forms_contact_form') {
      $suggestions[] = 'form_element__forms_contact';
    }
    if ($variables['element']['#form_id'] == 'forms_inscription_form') {
      $suggestions[] = 'form_element__forms_inscription';
    }
  }
  if ($hook == 'node' && isset($variables['node']) && $variables['node']->getType() == 'lot') {
    $suggestions[] = 'node__lot__full';
  }
}

/**
 * Implémente hook_theme().
 */
function forms_theme($existing, $type, $theme, $path) {
  return [
    'forms_contact_form' => [
      'render element' => 'form',
      'template' => 'forms-contact-form',
    ],
    'forms_inscription_form' => [
      'render element' => 'form',
      'template' => 'forms-inscription-form',
    ],
    'node__lot__full' => [
      'render element' => 'elements',
      'template' => 'node--lot--full',
    ],
  ];
}
